version: '3'
services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      restart: unless-stopped
      hostname: '192.168.11.66'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.11.66:9999'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
      ports:
        - '9999:9999'
        - '3322:22'
      volumes:
        - /root/app/docker/compose/gitlab/config:/etc/gitlab
        - /root/app/docker/compose/gitlab/data:/var/opt/gitlab
        - /root/app/docker/compose/gitlab/logs:/var/log/gitlab
